language: rust
sudo: required
rust:
  - stable
services:
  - docker
before_script: curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
script:
  - docker-compose run app sh -c "cargo build && cargo test"
